#ModTest.py
class MyList(list):
    def __init__(self, get_attr, *args, **kwargs):
        self._get_attr = get_attr
        super().__init__(self, *args, **kwargs)

    def __getitem__(self, key):
        return self._get_attr(key)

class multiAttrObj():
    # Init method cannot be changed...generated by SWIG (in real case)
    def __init__(self):
        self._attrA = "a b c d e f".split()
        self._attrB = "1 2 3 4 5".split()

    def __enter__(self):
        self._attrA2 = MyList(self.getAttrA)
        self._attrB2 = MyList(self.getAttrB)
        return self

    def __exit__(self, a,b,c):
        self._attrA = None
        self._attrB = None
        self._attrA2 = None
        self._attrB2 = None

    def nAttrA(self):
        return len(self._attrA)

    def nAttrB(self):
        return len(self._attrB)

    def getAttrA(self,i):
        print ("Getting A")
        return self._attrA[i]

    def getAttrB(self,i):
        print ("Getting B")
        return self._attrA[i]

    @property
    def AttrA(self):
        return self._attrA2

    @property
    def AttrB(self):
        return self._attrB2